### ISSUE TITLE
Extra line showing the items remaining in the shop

### ISSUE THREAD

**Issue by TheZenKitteh** [EpicEricEE/ShopChest#134]
Would be neat to show remaining quantity of items in the shop in the hologram maybe on an extra line. I'm not really sure if I could do it and if so how.

**Comment by EpicEricEE** [comment]
You can configure this in the `hologram-format.yml` file. There is the requirement `IN_STOCK`, that has to be compared against numbers, and the placeholder `%STOCK%`, that will be replaced with the amount of items in stock.

Here is an example of how to implement it:
```yml
3:			# Adjust this to the lines you already have in the file; should be one more
  options:	
    admin-shop:		# The amount in stock does not matter in an admin shop, so it's not shown
      format: ""	# An empty format will cause the line to not be displayed
      requirements:
        - ADMIN_SHOP

    empty:
      format: "Empty"
      requirements:
        - IN_STOCK < AMOUNT

    below-one-stack:
      format: "In Stock: %STOCK%"
      requirements:
        - IN_STOCK < 64
        - IN_STOCK > 0

    one-or-more-stacks-with-remainder:
      # The '%' character will give the remainder in a division, e.g. "10 % 3" is 1
      format: "In Stock: {(%STOCK% - (%STOCK% % 64)) / 64} Stk. {%STOCK% % 64}"
      requirements:
        - IN_STOCK > 64
        - IN_STOCK % 64 != 0

    exactly-one-or-more-stacks:
      format: "In Stock: &6{%STOCK% / 64} Stk."
      requirements:
        - IN_STOCK >= 64
        - IN_STOCK % 64 == 0
```
