### ISSUE TITLE
No buy/sell price displayed

### ISSUE THREAD

**Issue by maxcom1** [EpicEricEE/ShopChest#369]
Hi!
I have config:
```
  2:
    options:
      buy-and-sell:
        format: "Kup %BUY-PRICE% | %SELL-PRICE% Sprzedaj"
        requirements:
          - BUY_PRICE > 0
          - SELL_PRICE > 0

      only-buy:
        format: "Kup %BUY-PRICE%"
        requirements:
          - BUY_PRICE > 0

      only-sell:
        format: "Sprzedaj %SELL-PRICE%"
        requirements:
          - SELL_PRICE > 0
```
but sell and buy price are not displayed
 
![image](https://user-images.githubusercontent.com/46265094/126903967-53640b50-e9e8-4807-a995-594469b1756a.png)
